<?php

namespace BandMergerBundle\Repository;
use BandMergerBundle\Entity\User;
use BandMergerBundle\Entity\Band;
use Doctrine\ORM\EntityRepository;

/**
 * BandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BandRepository extends EntityRepository
{

}
